import keyMirror from 'fbjs/lib/keyMirror';

const ActionTypes = keyMirror({
  SET_USER_DATA: 'SET_USER_DATA',
  SET_API_TOKEN: 'SET_API_TOKEN',
  SET_NOTIFY: 'SET_NOTIFY',
  SET_LOCATION: 'SET_LOCATION',
  SET_LOCATION_STATUS: 'SET_LOCATION_STATUS',
  SET_INTERNET: 'SET_INTERNET',
  SET_SUCCESS: 'SET_SUCCESS',
  SET_USER_TYPE: 'SET_USER_TYPE',
  SET_PLAN_ACTIVE: 'SET_PLAN_ACTIVE',
  SET_CARD_LINK: 'SET_CARD_LINK',
  SET_IN_APP_NOTIFICATION: 'SET_IN_APP_NOTIFICATION',
  SELECTED_LANGUAGE :'SELECTED_LANGUAGE',
  SET_USER_PROFILE : 'SET_USER_PROFILE',
  SET_FILTERS: 'SET_FILTERS',
  SET_ADDTO_CART: 'SET_ADDTO_CART',
  SET_REMOVEFROM_CART: 'SET_REMOVEFROM_CART',
  SET_EMPTY_CART:'SET_EMPTY_CART',
  SET_UPDATE_CART:'SET_UPDATE_CART',
  RESTORE_MY_CART: 'RESTORE_MY_CART',
  SET_SAVED_ADDRESS:'SET_SAVED_ADDRESS',
  SET_SAVED_SHOPDETAIL:'SET_SAVED_SHOPDETAIL',
  SET_MYORDERSLIST_FILTERS:'SET_MYORDERSLIST_FILTERS',
  SET_REQUESTED_ITEMS_FILTERS : 'SET_REQUESTED_ITEMS_FILTERS',
  SET_SHOPKEEPER_ORDERS_FILTERS : 'SET_SHOPKEEPER_ORDERS_FILTERS',
  SET_SEARCH_FILTER : 'SET_SEARCH_FILTER',
  SET_FCM_TOKEN :  "SET_FCM_TOKEN",
  SET_SHOP_DETAILS:'SET_SHOP_DETAILS'
});

export default ActionTypes;
